import { spawn } from 'node:child_process';
import { createServer as createHttpServer } from 'node:http';
import { once } from 'node:events';
import { access, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { uiHtml } from './ui-html.mjs';
import { downloadVideo } from '../core/platform-runner.mjs';
import { normalizeNameTemplateForBatch, resolveBaseDir, resolveOutDir } from '../core/filename.mjs';
import { cdp, cookiesToHeader, getAllCookies, getCookiesForUrls, startCdpBrowser, waitForPage } from '../core/cdp-browser.mjs';
import { makeTempDir, removeTempDir } from '../core/temp-dir.mjs';
import { findBrowser } from '../platforms/index.mjs';
import { getVideoInfo as getBilibiliVideoInfo } from '../platforms/bilibili/index.mjs';
import { closeDouyinSession, createDouyinSession } from '../platforms/douyin/index.mjs';
import { closeKuaishouSession, createKuaishouSession } from '../platforms/kuaishou/index.mjs';
import { findYtDlp } from '../platforms/youtube/index.mjs';
import { chatWithAi, testAiConfig } from '../ai/client.mjs';
import { loadAiConfig, publicAiConfig, saveAiConfig } from '../ai/config.mjs';
import { analyzeTranscriptLocal } from '../ai/local-analysis.mjs';
import { buildSystemPrompt, buildTranscriptContext, quickAction } from '../ai/prompts.mjs';
import { extractSubtitlesFromUrl } from '../ai/subtitles.mjs';

function sendJson(res, status, data) {
  const body = JSON.stringify(data);
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(body),
  });
  res.end(body);
}

async function readJsonBody(req) {
  const chunks = [];
  for await (const chunk of req) {
    chunks.push(chunk);
  }
  if (!chunks.length) return {};
  return JSON.parse(Buffer.concat(chunks).toString('utf8'));
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function isYoutubeCookie(cookie) {
  const domain = String(cookie.domain || '').replace(/^\./, '').toLowerCase();
  return domain === 'youtube.com'
    || domain.endsWith('.youtube.com')
    || domain === 'google.com'
    || domain.endsWith('.google.com')
    || domain === 'youtu.be'
    || domain.endsWith('.youtu.be')
    || domain === 'youtube-nocookie.com'
    || domain.endsWith('.youtube-nocookie.com');
}

function youtubeCookieLoginLikely(cookies) {
  return (cookies || []).some((cookie) => {
    if (!isYoutubeCookie(cookie)) return false;
    return /^(LOGIN_INFO|SID|HSID|SSID|APISID|SAPISID|__Secure-\d?PSID|__Secure-\d?PAPISID)$/i.test(cookie.name || '');
  });
}

function cookiesToNetscape(cookies) {
  const rows = [
    '# Netscape HTTP Cookie File',
    '# Generated by 木辛说视频下载器. Keep this file private.',
  ];

  for (const cookie of cookies || []) {
    if (!isYoutubeCookie(cookie) || !cookie.name) continue;
    const rawDomain = String(cookie.domain || '').trim();
    if (!rawDomain) continue;
    const includeSubdomains = rawDomain.startsWith('.') ? 'TRUE' : 'FALSE';
    const domain = cookie.httpOnly ? `#HttpOnly_${rawDomain}` : rawDomain;
    const pathValue = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = Number.isFinite(Number(cookie.expires)) && Number(cookie.expires) > 0
      ? String(Math.floor(Number(cookie.expires)))
      : '0';
    rows.push([
      domain,
      includeSubdomains,
      pathValue,
      secure,
      expires,
      String(cookie.name),
      String(cookie.value || ''),
    ].join('\t'));
  }

  return `${rows.join('\n')}\n`;
}

function hasBilibiliLoginCookie(cookieHeader) {
  return /(?:^|;\s*)(SESSDATA|DedeUserID|bili_jct)=/.test(cookieHeader || '');
}

function qualityValueFromLabel(label) {
  const text = String(label || '').trim();
  const normalized = text.toLowerCase().replace(/\s+/g, '');
  if (!normalized) return '';
  if (/4k|2160/.test(normalized)) return '4k';
  if (/2k|1440/.test(normalized)) return '2k';
  if (/1080p?60|60帧/.test(normalized)) return '1080p60';
  if (/1080p?\+|高码率/.test(normalized)) return '1080p+';
  const matched = normalized.match(/(\d{3,4})p?/);
  if (matched) return matched[1];
  return '';
}

function parseQualityOptions(logs) {
  const line = logs.find((item) => /Available qualities:/i.test(item));
  const text = line ? line.replace(/^.*Available qualities:\s*/i, '').trim() : '';
  const options = [{ value: 'best', label: '自动选择最佳' }];
  const seen = new Set(options.map((item) => item.value));

  for (const rawPart of text.split(/[,，、]/)) {
    const label = rawPart.trim();
    const value = qualityValueFromLabel(label);
    if (!value || seen.has(value)) continue;
    seen.add(value);
    options.push({ value, label });
  }

  return {
    availableText: text,
    options,
    detected: options.length > 1,
  };
}

const BILIBILI_QUALITY_PROBES = [
  { value: '4k', qn: 120 },
  { value: '1080p60', qn: 116 },
  { value: '1080p+', qn: 112 },
  { value: '1080', qn: 80 },
  { value: '720', qn: 64 },
  { value: '480', qn: 32 },
  { value: '360', qn: 16 },
];

function bilibiliValueForQn(qn) {
  const matched = BILIBILI_QUALITY_PROBES.find((item) => item.qn === Number(qn));
  return matched?.value || String(qn || '');
}

async function detectBilibiliQualityOptions(videoUrl, cookieHeader) {
  const found = new Map();
  for (const probe of BILIBILI_QUALITY_PROBES) {
    const info = await getBilibiliVideoInfo(videoUrl, {
      quality: probe.value,
      bilibiliCookieHeader: cookieHeader || '',
    });
    const qn = Number(info.selectedQn) || probe.qn;
    if (!found.has(qn)) {
      found.set(qn, {
        value: bilibiliValueForQn(qn),
        label: info.selectedQuality || `${qn}`,
      });
    }
  }

  const options = [{ value: 'best', label: '自动选择最佳' }];
  for (const qn of [...found.keys()].sort((a, b) => b - a)) {
    const option = found.get(qn);
    if (option?.value) options.push(option);
  }

  const availableText = options.slice(1).map((item) => item.label).join(', ');
  return {
    availableText,
    options,
    detected: options.length > 1,
  };
}

function uniqueCookies(cookies) {
  const seen = new Set();
  const result = [];
  for (const cookie of cookies || []) {
    const key = `${cookie.domain || ''}\n${cookie.path || ''}\n${cookie.name || ''}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(cookie);
  }
  return result;
}

async function verifyBilibiliCookie(cookieHeader) {
  if (!cookieHeader) return false;
  try {
    const response = await fetch('https://api.bilibili.com/x/web-interface/nav', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
        Referer: 'https://www.bilibili.com/',
        Cookie: cookieHeader,
      },
    });
    if (!response.ok) return false;
    const json = await response.json();
    return Boolean(json?.data?.isLogin);
  } catch {
    return false;
  }
}

async function openUiBrowser(browserPath, uiUrl) {
  const profileDir = await makeTempDir('muxin-video-downloader-ui');
  const args = [
    `--user-data-dir=${profileDir}`,
    '--no-first-run',
    '--no-default-browser-check',
    `--app=${uiUrl}`,
  ];

  const proc = spawn(browserPath, args, {
    detached: true,
    stdio: 'ignore',
    windowsHide: false,
  });
  proc.unref();
  return { proc, profileDir };
}

async function runUiSession() {
  const browserPath = await findBrowser(null);
  const baseDir = resolveBaseDir();
  const defaultToolPaths = {
    ytDlpPath: path.join(baseDir, 'downloads', 'yt-dlp', 'yt-dlp.exe'),
    ffmpegPath: path.join(baseDir, 'downloads', 'ffmpeg', 'ffmpeg-release-essentials'),
  };
  const clients = new Set();
  const queue = [];
  const douyinSourceCache = new Map();
  const kuaishouSourceCache = new Map();
  const stats = { done: 0, failed: 0 };
  const bilibiliLogin = {
    browser: null,
    cookieHeader: '',
    loggedIn: false,
    uname: '',
    monitor: null,
    profileDir: path.join(baseDir, 'user-data', 'bilibili-profile'),
  };
  const youtubeLogin = {
    browser: null,
    browserChoice: '',
    browserLabel: '',
    browserMode: '',
    cookiesPath: path.join(baseDir, 'user-data', 'youtube-cookies.txt'),
    loggedIn: false,
    hasCookie: false,
    profileDir: path.join(baseDir, 'user-data', 'youtube-profile'),
  };
  let running = false;
  let stoppingDownloads = false;
  let activeJobController = null;
  let activeJobUrl = '';
  let activeDouyinSession = null;
  let activeKuaishouSession = null;
  const sourceCacheKey = (videoUrl) => String(videoUrl || '').trim();
  const getCachedSource = (cache, videoUrl) => {
    const key = sourceCacheKey(videoUrl);
    const cached = cache.get(key);
    if (!cached) return null;
    if (Date.now() - cached.savedAt > 10 * 60 * 1000) {
      cache.delete(key);
      return null;
    }
    return cached.payload;
  };
  const kuaishouCacheKey = (videoUrl) => String(videoUrl || '').trim();
  const getCachedKuaishouSource = (videoUrl) => {
    return getCachedSource(kuaishouSourceCache, videoUrl);
  };
  const getCachedDouyinSource = (videoUrl) => getCachedSource(douyinSourceCache, videoUrl);

  const emit = (event, data) => {
    const payload = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
    for (const client of clients) {
      client.write(payload);
    }
  };
  const emitQueue = () => emit('queue', { queued: queue.length });
  const emitRunState = () => emit('run-state', {
    running,
    stopping: stoppingDownloads,
    current: activeJobUrl,
    queued: queue.length,
  });
  let hadUiClient = false;
  let shutdownTimer = null;
  let shuttingDown = false;
  let uiBrowser = null;
  const shutdownServer = async () => {
    if (shuttingDown) return;
    shuttingDown = true;
    if (shutdownTimer) {
      clearTimeout(shutdownTimer);
      shutdownTimer = null;
    }
    for (const client of clients) {
      client.end();
    }
    clients.clear();
    await closeBilibiliLoginBrowser().catch(() => {});
    if (youtubeLogin.browser?.proc && !youtubeLogin.browser.proc.killed) {
      youtubeLogin.browser.proc.kill();
    }
    if (activeDouyinSession) {
      await closeDouyinSession(activeDouyinSession).catch(() => {});
      activeDouyinSession = null;
    }
    if (activeKuaishouSession) {
      await closeKuaishouSession(activeKuaishouSession).catch(() => {});
      activeKuaishouSession = null;
    }
    if (uiBrowser?.proc && !uiBrowser.proc.killed && uiBrowser.proc.exitCode === null) {
      uiBrowser.proc.kill();
      await Promise.race([
        once(uiBrowser.proc, 'exit'),
        sleep(2000),
      ]).catch(() => {});
    }
    await removeTempDir(uiBrowser?.profileDir);
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 1500).unref();
  };
  const scheduleShutdownIfUiClosed = () => {
    if (!hadUiClient || clients.size || shuttingDown) return;
    if (shutdownTimer) clearTimeout(shutdownTimer);
    shutdownTimer = setTimeout(() => {
      if (!clients.size) {
        shutdownServer().catch(() => process.exit(0));
      }
    }, 2500);
  };
  const cancelScheduledShutdown = () => {
    if (!shutdownTimer) return;
    clearTimeout(shutdownTimer);
    shutdownTimer = null;
  };
  const emitBilibiliLogin = () => emit('bilibili-login', {
    loggedIn: bilibiliLogin.loggedIn,
    hasCookie: Boolean(bilibiliLogin.cookieHeader),
    uname: bilibiliLogin.uname,
  });
  const emitYoutubeLogin = () => emit('youtube-login', {
    loggedIn: youtubeLogin.loggedIn,
    hasCookie: youtubeLogin.hasCookie,
  });
  const resolveYoutubeAuthOptions = (body, platform) => {
    if (platform !== 'youtube') {
      return {
        ytDlpCookiesPath: '',
        ytDlpCookiesFromBrowser: '',
      };
    }
    const explicitCookiesPath = body.ytDlpCookiesPath ? String(body.ytDlpCookiesPath) : '';
    const auth = String(body.youtubeAuth || 'none').trim().toLowerCase();
    if (auth === 'app' && youtubeLogin.browserMode === 'firefox' && youtubeLogin.hasCookie) {
      return {
        ytDlpCookiesPath: '',
        ytDlpCookiesFromBrowser: `firefox:${youtubeLogin.browser?.profileDir || youtubeLogin.profileDir}`,
      };
    }
    return {
      ytDlpCookiesPath: explicitCookiesPath || (auth === 'app' && youtubeLogin.hasCookie ? youtubeLogin.cookiesPath : ''),
      ytDlpCookiesFromBrowser: '',
    };
  };
  const browserChoiceLabel = (choice) => ({
    chrome: 'Chrome',
    edge: 'Edge',
    firefox: 'Firefox',
  }[choice] || 'Chrome');
  const findYoutubeLoginBrowser = async (choiceInput) => {
    const choice = String(choiceInput || 'chrome').trim().toLowerCase();
    const localAppData = process.env.LOCALAPPDATA || '';
    const candidatesByChoice = {
      chrome: [
        process.env.CHROME_PATH,
        'C:/Program Files/Google/Chrome/Application/chrome.exe',
        'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
      ],
      edge: [
        process.env.EDGE_PATH,
        'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
        'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
      ],
      firefox: [
        process.env.FIREFOX_PATH,
        'C:/Program Files/Mozilla Firefox/firefox.exe',
        'C:/Program Files (x86)/Mozilla Firefox/firefox.exe',
        localAppData ? path.join(localAppData, 'Mozilla Firefox', 'firefox.exe') : '',
      ],
    };
    const candidates = candidatesByChoice[choice];
    if (!candidates) {
      return { choice: 'chrome', label: browserChoiceLabel('chrome'), path: browserPath };
    }
    for (const candidate of candidates.filter(Boolean)) {
      if (await fileExists(candidate)) {
        return { choice, label: browserChoiceLabel(choice), path: candidate };
      }
    }
    throw new Error(`没有找到 ${browserChoiceLabel(choice)}，请换一个 YouTube 登录浏览器`);
  };

  const closeBilibiliLoginBrowser = async () => {
    if (bilibiliLogin.monitor) {
      clearInterval(bilibiliLogin.monitor);
      bilibiliLogin.monitor = null;
    }
    const browser = bilibiliLogin.browser;
    bilibiliLogin.browser = null;
    if (browser?.page?.webSocketDebuggerUrl) {
      await cdp(browser.page.webSocketDebuggerUrl, 'Browser.close', {}, 3000).catch(() => {});
    }
    if (browser?.proc && !browser.proc.killed && browser.proc.exitCode === null) {
      browser.proc.kill();
    }
  };

  const readBilibiliCookieFromBrowser = async () => {
    const browser = bilibiliLogin.browser;
    if (!browser?.port) return false;
    browser.page = await waitForPage(
      browser.port,
      10_000,
      (page) => /bilibili\.com/i.test(String(page.url || '')),
    );
    const cookies = uniqueCookies([
      ...await getAllCookies(browser.page),
      ...await getCookiesForUrls(browser.page, [
        'https://www.bilibili.com/',
        'https://passport.bilibili.com/',
        'https://api.bilibili.com/',
      ]),
    ]);
    const cookieHeader = cookiesToHeader(cookies, 'bilibili.com');
    const verified = await verifyBilibiliCookie(cookieHeader);
    if (!verified) {
      return false;
    }
    bilibiliLogin.cookieHeader = cookieHeader;
    bilibiliLogin.loggedIn = true;
    bilibiliLogin.uname = '';
    emitBilibiliLogin();
    return true;
  };

  const startBilibiliLoginMonitor = () => {
    if (bilibiliLogin.monitor) clearInterval(bilibiliLogin.monitor);
    let attempts = 0;
    bilibiliLogin.monitor = setInterval(() => {
      attempts += 1;
      readBilibiliCookieFromBrowser()
        .then(async (success) => {
          if (success) {
            emit('log', { message: 'Bilibili 登录成功，后续高码率下载会使用该登录态。' });
            await closeBilibiliLoginBrowser();
          } else if (attempts >= 180) {
            clearInterval(bilibiliLogin.monitor);
            bilibiliLogin.monitor = null;
            emit('log', { message: 'Bilibili 登录等待超时，可以重新点击高码率登录。' });
          }
        })
        .catch(() => {});
    }, 1500);
  };

  const ensureBilibiliLoginBrowser = async () => {
    if (bilibiliLogin.browser?.port) {
      return bilibiliLogin.browser;
    }
    await mkdir(bilibiliLogin.profileDir, { recursive: true });
    bilibiliLogin.browser = await startCdpBrowser(browserPath, {
      url: 'https://passport.bilibili.com/login',
      profileDir: bilibiliLogin.profileDir,
      showBrowser: true,
      timeoutMs: 30_000,
      pagePredicate: (page) => String(page.url || '').includes('bilibili.com'),
      waitForPage: false,
    });
    await sleep(600);
    try {
      bilibiliLogin.browser.page = await waitForPage(
        bilibiliLogin.browser.port,
        15_000,
        (page) => /bilibili\.com/i.test(String(page.url || '')),
      );
    } catch {
      bilibiliLogin.browser = null;
      throw new Error('Bilibili 登录窗口已打开，但程序没有连上登录窗口。请关闭该窗口后重试。');
    }
    startBilibiliLoginMonitor();
    return bilibiliLogin.browser;
  };

  const refreshBilibiliCookie = async () => {
    if (!bilibiliLogin.browser?.port) {
      return {
        loggedIn: bilibiliLogin.loggedIn,
        hasCookie: Boolean(bilibiliLogin.cookieHeader),
        uname: bilibiliLogin.uname,
      };
    }
    await readBilibiliCookieFromBrowser();
    bilibiliLogin.uname = '';
    emitBilibiliLogin();
    return {
      loggedIn: bilibiliLogin.loggedIn,
      hasCookie: Boolean(bilibiliLogin.cookieHeader),
      uname: bilibiliLogin.uname,
    };
  };

  const hasYoutubeLoginBrowser = () => Boolean(
    youtubeLogin.browser?.proc
      && !youtubeLogin.browser.proc.killed
      && youtubeLogin.browser.proc.exitCode === null,
  );
  const youtubeLoginBrowserAlive = async () => {
    if (!hasYoutubeLoginBrowser()) return false;
    if (youtubeLogin.browserMode === 'firefox') return true;
    try {
      const response = await fetch(`http://127.0.0.1:${youtubeLogin.browser.port}/json/version`);
      return response.ok;
    } catch {
      youtubeLogin.browser = null;
      youtubeLogin.browserChoice = '';
      youtubeLogin.browserLabel = '';
      youtubeLogin.browserMode = '';
      return false;
    }
  };
  const probeFirefoxYoutubeLogin = async () => {
    const profileDir = youtubeLogin.browser?.profileDir || youtubeLogin.profileDir;
    const ytDlpPath = await findYtDlp(defaultToolPaths.ytDlpPath);
    if (!ytDlpPath) {
      throw new Error('没有找到 yt-dlp，无法读取 Firefox 登录状态');
    }
    const result = await new Promise((resolve) => {
      const proc = spawn(ytDlpPath, [
        '--ignore-config',
        '--cookies-from-browser',
        `firefox:${profileDir}`,
        '--simulate',
        '--skip-download',
        '--no-warnings',
        'https://www.youtube.com/',
      ], {
        stdio: ['ignore', 'pipe', 'pipe'],
        windowsHide: true,
      });
      let stdout = '';
      let stderr = '';
      proc.stdout.setEncoding('utf8');
      proc.stderr.setEncoding('utf8');
      proc.stdout.on('data', (chunk) => { stdout += chunk; });
      proc.stderr.on('data', (chunk) => { stderr += chunk; });
      proc.on('error', (error) => resolve({ ok: false, error: error.message }));
      proc.on('exit', (code) => resolve({
        ok: code === 0,
        error: code === 0 ? '' : (stderr || stdout || `yt-dlp exited with code ${code}`).trim(),
      }));
    });
    youtubeLogin.hasCookie = result.ok;
    youtubeLogin.loggedIn = result.ok;
    emitYoutubeLogin();
    if (!result.ok) {
      throw new Error(`读取 Firefox 登录状态失败：${result.error || '没有读取到 YouTube Cookie'}`);
    }
    return { loggedIn: youtubeLogin.loggedIn, hasCookie: youtubeLogin.hasCookie };
  };

  const ensureYoutubeLoginBrowser = async (loginBrowser = 'default') => {
    if (await youtubeLoginBrowserAlive()) {
      return youtubeLogin.browser;
    }
    const resolvedBrowser = await findYoutubeLoginBrowser(loginBrowser);
    youtubeLogin.browserChoice = resolvedBrowser.choice;
    youtubeLogin.browserLabel = resolvedBrowser.label;
    youtubeLogin.browserMode = resolvedBrowser.choice === 'firefox' ? 'firefox' : 'cdp';
    if (youtubeLogin.browserMode === 'firefox') {
      await mkdir(youtubeLogin.profileDir, { recursive: true });
      const proc = spawn(resolvedBrowser.path, [
        '-no-remote',
        '-profile',
        youtubeLogin.profileDir,
        'https://www.youtube.com/',
      ], {
        detached: false,
        stdio: 'ignore',
        windowsHide: false,
      });
      youtubeLogin.browser = {
        proc,
        profileDir: youtubeLogin.profileDir,
        port: null,
        page: null,
      };
      await sleep(600);
      if (proc.exitCode !== null) {
        youtubeLogin.browser = null;
        youtubeLogin.browserMode = '';
        throw new Error('Firefox 登录窗口启动后立即退出，请换 Chrome 或 Edge 重试');
      }
      return youtubeLogin.browser;
    }
    youtubeLogin.browser = await startCdpBrowser(resolvedBrowser.path, {
      url: 'https://www.youtube.com/',
      profileDir: youtubeLogin.profileDir,
      showBrowser: true,
      timeoutMs: 30_000,
      pagePredicate: (page) => /(?:youtube|google)\.com/i.test(String(page.url || '')),
      waitForPage: false,
    });
    await sleep(600);
    if (youtubeLogin.browser.proc.exitCode !== null) {
      youtubeLogin.browser = null;
      youtubeLogin.browserMode = '';
      throw new Error(`YouTube 登录窗口启动后立即退出，请换一个登录浏览器重试`);
    }
    return youtubeLogin.browser;
  };

  const refreshYoutubeCookie = async () => {
    if (youtubeLogin.browserMode === 'firefox') {
      return probeFirefoxYoutubeLogin();
    }
    const browser = await ensureYoutubeLoginBrowser();
    browser.page = await waitForPage(
      browser.port,
      10_000,
      (page) => /(?:youtube|google)\.com/i.test(String(page.url || '')),
    );
    const cookies = await getAllCookies(browser.page);
    const relevantCookies = cookies.filter(isYoutubeCookie);
    await mkdir(path.dirname(youtubeLogin.cookiesPath), { recursive: true });
    await writeFile(youtubeLogin.cookiesPath, cookiesToNetscape(relevantCookies), 'utf8');
    youtubeLogin.hasCookie = relevantCookies.length > 0;
    youtubeLogin.loggedIn = youtubeCookieLoginLikely(relevantCookies);
    emitYoutubeLogin();
    return {
      loggedIn: youtubeLogin.loggedIn,
      hasCookie: youtubeLogin.hasCookie,
    };
  };
  const refreshYoutubeCookieForRequest = async (body, platform) => {
    if (platform !== 'youtube') return;
    if (String(body.youtubeAuth || 'none').trim().toLowerCase() !== 'app') return;
    if (hasYoutubeLoginBrowser()) {
      await refreshYoutubeCookie();
    }
    if (youtubeLogin.browserMode === 'firefox') {
      await probeFirefoxYoutubeLogin();
      return;
    }
    youtubeLogin.hasCookie = youtubeLogin.hasCookie || await fileExists(youtubeLogin.cookiesPath);
    if (!youtubeLogin.hasCookie) {
      throw new Error('YouTube 已选择本程序登录窗口，但还没有读取到登录状态。请先打开 YouTube 登录窗口并登录，再点“确认登录来源”或直接重新识别画质。');
    }
  };

  const processQueue = async () => {
    if (running) return;
    running = true;
    stoppingDownloads = false;
    emitRunState();
    let douyinSession = null;
    let kuaishouSession = null;
    try {
      while (queue.length) {
        if (stoppingDownloads) break;
        const job = queue.shift();
        activeJobUrl = job.url;
        activeJobController = new AbortController();
        emitQueue();
        emitRunState();
        emit('log', { message: `开始任务：${job.url}` });
        try {
          let jobOptions = { ...job.options, signal: activeJobController.signal };
          if (jobOptions.platform === 'douyin' && !jobOptions.douyinResolvedInfo) {
            if (kuaishouSession) {
              await closeKuaishouSession(kuaishouSession, jobOptions).catch(() => {});
              kuaishouSession = null;
            }
            if (!douyinSession) {
              emit('log', { message: '抖音批量任务将复用同一个浏览器窗口。' });
              douyinSession = await createDouyinSession(browserPath, {
                timeoutMs: jobOptions.timeoutMs,
              });
              activeDouyinSession = douyinSession;
            }
            jobOptions = { ...jobOptions, douyinSession };
          } else if (jobOptions.platform === 'kuaishou' && !jobOptions.kuaishouResolvedInfo) {
            if (douyinSession) {
              await closeDouyinSession(douyinSession, jobOptions).catch(() => {});
              douyinSession = null;
              activeDouyinSession = null;
            }
            if (!kuaishouSession) {
              emit('log', { message: '快手批量任务将复用同一个浏览器窗口。' });
              kuaishouSession = await createKuaishouSession(browserPath, {
                timeoutMs: jobOptions.timeoutMs,
              });
              activeKuaishouSession = kuaishouSession;
            }
            jobOptions = { ...jobOptions, kuaishouSession };
          } else {
            if (douyinSession && jobOptions.platform !== 'douyin') {
              await closeDouyinSession(douyinSession, jobOptions).catch(() => {});
              douyinSession = null;
              activeDouyinSession = null;
            }
            if (kuaishouSession && jobOptions.platform !== 'kuaishou') {
              await closeKuaishouSession(kuaishouSession, jobOptions).catch(() => {});
              kuaishouSession = null;
              activeKuaishouSession = null;
            }
          }
          const output = await downloadVideo(job.url, {
            ...jobOptions,
            onLog: (message) => emit('log', { message }),
            onProgress: (payload) => emit('progress', payload),
          }, browserPath);
          stats.done += 1;
          emit('done', {
            queued: queue.length,
            done: stats.done,
            failed: stats.failed,
            output,
          });
        } catch (error) {
          if (activeJobController?.signal.aborted || /任务已终止|aborted|abort/i.test(error.message || '')) {
            emit('log', { message: `任务已终止：${job.url}` });
            emit('progress', { percent: 0 });
            continue;
          }
          stats.failed += 1;
          emit('error-job', {
            queued: queue.length,
            done: stats.done,
            failed: stats.failed,
            message: error.message,
          });
        }
      }
    } finally {
      activeJobController = null;
      activeJobUrl = '';
      if (douyinSession) {
        await closeDouyinSession(douyinSession).catch(() => {});
        activeDouyinSession = null;
      }
      if (kuaishouSession) {
        await closeKuaishouSession(kuaishouSession).catch(() => {});
        activeKuaishouSession = null;
      }
      running = false;
      stoppingDownloads = false;
      emitRunState();
    }
  };

  const server = createHttpServer(async (req, res) => {
    try {
      const url = new URL(req.url || '/', 'http://127.0.0.1');
      if (req.method === 'GET' && url.pathname === '/') {
        const body = uiHtml(defaultToolPaths);
        res.writeHead(200, {
          'content-type': 'text/html; charset=utf-8',
          'content-length': Buffer.byteLength(body),
        });
        res.end(body);
        return;
      }
      if (req.method === 'GET' && url.pathname === '/events') {
        res.writeHead(200, {
          'content-type': 'text/event-stream; charset=utf-8',
          'cache-control': 'no-cache',
          connection: 'keep-alive',
        });
        hadUiClient = true;
        cancelScheduledShutdown();
        clients.add(res);
        res.write(`event: queue\ndata: ${JSON.stringify({ queued: queue.length })}\n\n`);
        res.write(`event: run-state\ndata: ${JSON.stringify({ running, stopping: stoppingDownloads, current: activeJobUrl, queued: queue.length })}\n\n`);
        res.write(`event: bilibili-login\ndata: ${JSON.stringify({ loggedIn: bilibiliLogin.loggedIn, hasCookie: Boolean(bilibiliLogin.cookieHeader), uname: bilibiliLogin.uname })}\n\n`);
        res.write(`event: youtube-login\ndata: ${JSON.stringify({ loggedIn: youtubeLogin.loggedIn, hasCookie: youtubeLogin.hasCookie })}\n\n`);
        req.on('close', () => {
          clients.delete(res);
          scheduleShutdownIfUiClosed();
        });
        return;
      }
      if (req.method === 'GET' && url.pathname === '/api/ai/config') {
        const config = await loadAiConfig();
        sendJson(res, 200, { ok: true, config: publicAiConfig(config) });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/ai/config') {
        const body = await readJsonBody(req);
        const config = await saveAiConfig(body);
        sendJson(res, 200, { ok: true, config: publicAiConfig(config) });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/ai/test') {
        const body = await readJsonBody(req);
        const config = await saveAiConfig(body);
        const message = await testAiConfig(config);
        sendJson(res, 200, { ok: true, message, config: publicAiConfig(config) });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/ai/local-analyze') {
        const body = await readJsonBody(req);
        const transcript = String(body.transcript || '').trim();
        if (!transcript) {
          sendJson(res, 400, { ok: false, error: '请先粘贴字幕、转写稿或视频内容文本。' });
          return;
        }
        const analysis = analyzeTranscriptLocal(transcript, String(body.platform || 'general'));
        sendJson(res, 200, { ok: true, analysis });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/ai/extract-subtitles') {
        const body = await readJsonBody(req);
        const videoUrl = String(body.url || '').trim();
        const ytDlpPath = await findYtDlp(body.ytDlpPath ? String(body.ytDlpPath) : defaultToolPaths.ytDlpPath);
        const subtitles = await extractSubtitlesFromUrl(videoUrl, ytDlpPath);
        sendJson(res, 200, { ok: true, subtitles });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/ai/chat') {
        const body = await readJsonBody(req);
        const config = await loadAiConfig();
        const platform = String(body.platform || 'general');
        const transcript = String(body.transcript || '');
        const sourceUrl = String(body.sourceUrl || '');
        const history = Array.isArray(body.messages) ? body.messages : [];
        const action = quickAction(String(body.action || ''));
        const prompt = action?.prompt || String(body.prompt || '').trim();
        if (!prompt && !history.length) {
          sendJson(res, 400, { ok: false, error: '请输入想问 AI 的问题，或点击一个二创快捷按钮。' });
          return;
        }
        const messages = [
          { role: 'system', content: buildSystemPrompt(platform) },
          { role: 'user', content: buildTranscriptContext(transcript, sourceUrl) },
          ...history.map((item) => ({
            role: item?.role === 'assistant' ? 'assistant' : 'user',
            content: String(item?.content || ''),
          })),
        ];
        if (prompt) messages.push({ role: 'user', content: prompt });
        const answer = await chatWithAi(config, messages);
        sendJson(res, 200, { ok: true, answer });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/bilibili/login') {
        await closeBilibiliLoginBrowser();
        bilibiliLogin.cookieHeader = '';
        bilibiliLogin.loggedIn = false;
        bilibiliLogin.uname = '';
        emitBilibiliLogin();
        await ensureBilibiliLoginBrowser();
        sendJson(res, 200, { ok: true });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/bilibili/check-login') {
        const status = await refreshBilibiliCookie();
        sendJson(res, 200, { ok: true, ...status });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/youtube/login') {
        const body = await readJsonBody(req);
        const reused = hasYoutubeLoginBrowser();
        await ensureYoutubeLoginBrowser(body.loginBrowser);
        sendJson(res, 200, {
          ok: true,
          reused,
          browser: youtubeLogin.browserChoice,
          browserLabel: youtubeLogin.browserLabel,
        });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/youtube/check-login') {
        const status = await refreshYoutubeCookie();
        sendJson(res, 200, { ok: true, ...status });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/qualities') {
        const body = await readJsonBody(req);
        const videoUrl = String(body.url || '').trim();
        if (!videoUrl) {
          sendJson(res, 400, { ok: false, error: '请先粘贴一条链接。' });
          return;
        }
        const platform = body.platform ? String(body.platform) : '';
        if (platform === 'bilibili' && bilibiliLogin.browser?.port) {
          await refreshBilibiliCookie().catch(() => {});
        }
        if (platform === 'bilibili') {
          const parsed = await detectBilibiliQualityOptions(videoUrl, bilibiliLogin.cookieHeader);
          emit('log', {
            message: parsed.detected
              ? `Bilibili 实际可选画质：${parsed.availableText}`
              : 'Bilibili 未识别到多个实际可选画质，将使用自动选择最佳。',
          });
          sendJson(res, 200, {
            ok: true,
            logs: [],
            ...parsed,
          });
          return;
        }
        const logs = [];
        const timeoutSeconds = Number(body.timeoutSeconds) || 180;
        await refreshYoutubeCookieForRequest(body, platform);
        const authOptions = resolveYoutubeAuthOptions(body, platform);
        const probeOutput = await downloadVideo(videoUrl, {
          outDir: resolveOutDir('videos'),
          nameTemplate: '%title%_%id%.mp4',
          browser: null,
          showBrowser: false,
          keepProfile: false,
          overwrite: false,
          infoOnly: true,
          platform,
          quality: 'best',
          timeoutMs: Math.max(30, timeoutSeconds) * 1000,
          bilibiliCookieHeader: platform === 'bilibili' ? bilibiliLogin.cookieHeader : '',
          ffmpegPath: body.ffmpegPath ? String(body.ffmpegPath) : '',
          ytDlpPath: body.ytDlpPath ? String(body.ytDlpPath) : '',
          ...authOptions,
          onLog: (message) => {
            logs.push(String(message || ''));
            emit('log', { message });
          },
          onProgress: (payload) => emit('progress', payload),
        }, browserPath);
        if (platform === 'douyin' && probeOutput?.info?.src) {
          douyinSourceCache.set(sourceCacheKey(videoUrl), {
            savedAt: Date.now(),
            payload: probeOutput,
          });
          emit('log', { message: '已锁定当前抖音视频源，稍后点击下载会直接使用这个视频，不再重新打开页面。' });
        }
        if (platform === 'kuaishou' && probeOutput?.info?.src) {
          kuaishouSourceCache.set(sourceCacheKey(videoUrl), {
            savedAt: Date.now(),
            payload: probeOutput,
          });
          emit('log', { message: '已锁定当前快手视频源，稍后点击下载会直接使用这个视频，不再重新打开页面。' });
        }
        const parsed = parseQualityOptions(logs);
        sendJson(res, 200, {
          ok: true,
          logs,
          ...parsed,
        });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/download') {
        const body = await readJsonBody(req);
        const urls = Array.isArray(body.urls) ? body.urls.map((item) => String(item).trim()).filter(Boolean) : [];
        if (!urls.length) {
          sendJson(res, 400, { ok: false, error: '没有提供链接。' });
          return;
        }
        if (String(body.platform || '') === 'bilibili' && bilibiliLogin.browser?.port) {
          await refreshBilibiliCookie().catch(() => {});
        }
        const platform = body.platform ? String(body.platform) : '';
        await refreshYoutubeCookieForRequest(body, platform);
        const authOptions = resolveYoutubeAuthOptions(body, platform);
        const timeoutSeconds = Number(body.timeoutSeconds) || 180;
        const requestedNameTemplate = body.nameTemplate ? String(body.nameTemplate) : '%title%_%id%.mp4';
        const nameTemplate = normalizeNameTemplateForBatch(requestedNameTemplate, urls.length);
        const options = {
          outDir: resolveOutDir(body.outDir),
          nameTemplate,
          browser: null,
          showBrowser: false,
          keepProfile: false,
          overwrite: Boolean(body.overwrite),
          infoOnly: false,
          platform,
          quality: body.quality ? String(body.quality).toLowerCase() : 'best',
          timeoutMs: Math.max(30, timeoutSeconds) * 1000,
          bilibiliCookieHeader: String(body.platform || '') === 'bilibili' ? bilibiliLogin.cookieHeader : '',
          ffmpegPath: body.ffmpegPath ? String(body.ffmpegPath) : '',
          ytDlpPath: body.ytDlpPath ? String(body.ytDlpPath) : '',
          ...authOptions,
        };
        for (const item of urls) {
          const jobOptions = { ...options };
          if (jobOptions.platform === 'douyin') {
            const cached = getCachedDouyinSource(item);
            if (cached?.info?.src) {
              jobOptions.douyinResolvedInfo = cached;
              emit('log', { message: `抖音已使用识别画质时锁定的视频源：${item}` });
            }
          }
          if (jobOptions.platform === 'kuaishou') {
            const cached = getCachedKuaishouSource(item);
            if (cached?.info?.src) {
              jobOptions.kuaishouResolvedInfo = cached;
              emit('log', { message: `快手已使用识别画质时锁定的视频源：${item}` });
            }
          }
          queue.push({ url: item, options: jobOptions });
        }
        if (nameTemplate !== requestedNameTemplate) {
          emit('log', { message: `文件名规则已调整为：${nameTemplate}` });
        }
        emitQueue();
        processQueue().catch((error) => emit('log', { message: `队列异常：${error.message}` }));
        sendJson(res, 200, { ok: true, added: urls.length });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/cancel') {
        const cleared = queue.length;
        const hadRunning = running;
        queue.length = 0;
        stoppingDownloads = true;
        if (activeJobController && !activeJobController.signal.aborted) {
          activeJobController.abort();
        }
        if (activeDouyinSession) {
          await closeDouyinSession(activeDouyinSession).catch(() => {});
          activeDouyinSession = null;
        }
        if (activeKuaishouSession) {
          await closeKuaishouSession(activeKuaishouSession).catch(() => {});
          activeKuaishouSession = null;
        }
        if (!hadRunning) {
          stoppingDownloads = false;
        }
        emitQueue();
        emitRunState();
        emit('progress', { percent: 0 });
        emit('log', { message: cleared ? `已终止当前任务，并清空等待队列 ${cleared} 条。` : '已请求终止当前下载任务。' });
        sendJson(res, 200, { ok: true, cleared, running });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/platform-switch') {
        if (!running) {
          if (activeDouyinSession) {
            await closeDouyinSession(activeDouyinSession).catch(() => {});
            activeDouyinSession = null;
          }
          if (activeKuaishouSession) {
            await closeKuaishouSession(activeKuaishouSession).catch(() => {});
            activeKuaishouSession = null;
          }
        }
        sendJson(res, 200, { ok: true });
        return;
      }
      if (req.method === 'POST' && url.pathname === '/api/quit') {
        sendJson(res, 200, { ok: true });
        setTimeout(() => {
          shutdownServer().catch(() => process.exit(0));
        }, 100);
        return;
      }
      sendJson(res, 404, { ok: false, error: 'Not found' });
    } catch (error) {
      sendJson(res, 500, { ok: false, error: error.message });
    }
  });

  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  const { port } = server.address();
  const uiUrl = `http://127.0.0.1:${port}/`;
  console.log(`UI: ${uiUrl}`);

  uiBrowser = await openUiBrowser(browserPath, uiUrl);
}

export { runUiSession };
